### ISSUE TITLE
Tag a release for MELPA Stable

### ISSUE THREAD

**Issue by cap10morgan** [Sterlingg/json-snatcher#8]
Can you push a tag to GitHub so that a release will go out to MELPA Stable?

Would be as simple as:

`git tag 1.0.0`
`git push --tags origin`

This will help make json-mode installable from MELPA Stable once again (it depends on this now in version 1.5.0).

Thanks!

**Comment by markhellewell** [comment]
yes please!

**Comment by bostonaholic** [comment]
:+1:

**Comment by Valdaer** [comment]
:+1:

**Comment by Sterlingg** [comment]
@cap10morgan Done, let me know if this doesn't fix the issue.

**Comment by markhellewell** [comment]
Awesome, thanks @Sterlingg !

**Comment by cap10morgan** [comment]
@Sterlingg  Looks great, thanks!
